spring.datasource.url=jdbc:mysql://mysql:3306/mainmarketdb
spring.datasource.username=mainmarket
spring.datasource.password=mainmarket123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

spring.h2.console.enabled=false

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data-mysql.sql